<?php
	include('../do/nav.php');
	$PROJECT_NAME = 'Ambient Trust';
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Zachary Zimmerman - <?php echo($PROJECT_NAME); ?></title>
	<link rel="stylesheet" href="../styles.css" type="text/css" />
	<link rel="stylesheet" href="../css/lightbox.css" type="text/css" media="screen" />
	<script type="text/javascript" src="../js/prototype.js"></script>
	<script type="text/javascript" src="../js/scriptaculous.js?load=effects,builder"></script>
	<script type="text/javascript" src="../js/lightbox.js"></script>
    <script type="text/javascript">
	
	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-6331853-2']);
	  _gaq.push(['_setDomainName', '.zachzimm.com']);
	  _gaq.push(['_trackPageview']);
	
	  (function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	
	</script>
</head>
<body>

	<div class="container">
    	<div id="header">
        	<div class="topSpaceHolder">
            	&nbsp;
            </div>
<?php
			printNav(3);
?>
            <div class="navSpaceHolder">
            
            </div>
        </div>
        <div id="content">
        
        	<div class="project">
				<h2><?php echo($PROJECT_NAME); ?></h2>
				<hr />
				<div class="overviewContainer">
					<div class="overviewLeft">
                   	<table class="projectOverview">
						<tr>
							<th>When</th>
							<td>May 2008 - May 2010</td>
						</tr>
						<tr>
							<th>Technologies</th>
							<td>Arduino, C, C#, PHP, MySQL, Javascript, XPCOM, XUL, XML</td>
						</tr>
						<tr>
							<th>Project Site</th>
							<td>
								<a href="http://ethos.soic.indiana.edu/projects/ambient-trust">ETHOS - Ambient Trust</a><br/>
								<a href="http://www.ljean.com/NetTrust/">Net Trust</a>
							</td>
						</tr>
						<tr>
							<th>Source</th>
							<td><a href="http://code.google.com/p/ambienttrust/">Google Code - Ambient Trust</a><br/>
							<a href="http://code.google.com/p/nettrust/source/browse/branches/AmbientTrust/">Google Code - Net Trust (branch)</a></td>
						</tr>
						<tr>
							<th>License</th>
							<td>Apache 2.0</td>
						</tr>
					</table>
					</div>
					<div class="overviewRight">
						<a href="../images/ambientTrustBig.gif" rel="lightbox" title="Ambient Trust in action"><img src="../images/ambientTrustSmall.gif" alt="Screenshot of Ambient Trust in action"/></a>
					</div>
				</div>
                <div id="education" class="resumeSection">
					<h3>Description</h3>
                    <hr />
					<p>During my undergraduate studies I was chosen by <a href="http://www.ljean.com">Professor L. Jean Camp</a>, the director of the Security Informatics Program at Indiana University, to have the opportunity of contributing to an open source project called <a href="netTrust.php">Net Trust</a>
					as part of a funded research assistantship made possible by Google and the National Science Foundation. My main contribution to this project was the design, maintenance,
					and development of an alternative interface called Ambient Trust. The goal of this alternative display was to simplify the information conveyed by an anti-phishing
					browser toolbar to a format more easily perceved by older adults (65 years old and above).</p>
					<h3>Design</h3>
					<p>Ambient Trust itself is a set of LED lights enclosed in a frosted plastic cube, with two arrows on the side of the cube that are touch responsive. 
					The LEDs and frosted plastic blended the colors of the red and green LEDs to produce different shades of red, yellow and green. The color displayed by
					the cube represented the average of the user's friends' ratings of the current website being browsed in Firefox. If average rating was negative, the cube
					would pulse with a red color, indicating danger. If the rating was neutral the cube would glow yellow, and if the rating was positive the cube would glow green.
					The cube would also pulse red if SiteAdvisor or another third party rating authority deems a website a danger.</p>
					<p>To rate a website (generally negatively), instead of interacting with the browser toolbar the user could touch the touch-sensitive arrows on the sides of the cube.
					Positive ratings are automatically generated by Net Trust based on how many times the user and his or her friends visited the website.</p>
					<h3>Development</h3>
					<p>The implementation of this project consisted of:
					<ul>
						<li>An Arduino Microcontroller with multiple red and green LEDs soldered onto a custom shield attached to the microcontroller's board, with a layer of wax paper to help diffuse and blend light from the LEDs</li>
						<li>Two capacitive touch sensors connected with wires soldered to the custom shield attached to the microcontroller board</li>
						<li>A custom-fabricated frosted plastic cube with two metal arrows fitted with the two capacitive touch sensors</li>
						<li>A small Arduino <a href="http://code.google.com/p/ambienttrust/source/browse/trunk/Firmware/firmware.pde">"sketch"</a> developed in C to communicate with
							the browser toolbar via a USB Serial interface, monitor the touch sensors, and control all LEDs</li>
						<li>A <a href="http://code.google.com/p/ambienttrust/source/browse/trunk/Toolbar/">branched copy</a> of Net Trust with <a href="http://code.google.com/p/ambienttrust/source/browse/trunk/Toolbar/chrome/content/ambientTrust.js">modifications</a> added to support the hardware</li>
						<li>A program running on the user's machine called "Serproxy"</li>
					</ul>
					<h3>Publications</h3>
					<h4>Poster Papers</h4>
					<ul>
						<li><B>Schall-Zimmerman, Z.</B> (2008). <i>Surfing with Ambient Trust.</i> Conference poster presentation, Accepted. Collection: Telecommunications Policy Research Conference. 28-30 Sept 2008, Arlington VA.</li>
					</ul>
					<h5>Poster Sessions</h5>
					<ul>
						<li>Schall-Zimmerman, Z., & Camp, L. J. (2009). <i>Ambient Trust Cube.</i> Presented as Demo/Poster at <a href="http://www.thei3p.org/events/past_events.html">I3P Insider Threats: Strategies for Staying Secure, 2009</a>.</li>
						<li>Schall-Zimmerman, Z., & Camp, L. J. (2008). <i>Ambient Trust Cube.</i> Presented as Demo/Poster at <a href="http://www.tprcweb.com/">TPRC 2008</a>.</li>
						<li>Schall-Zimmerman, Z., & Camp, L. J. (2008). <i>SWAT: Surfing with Ambient Trust.</i> Presented as Demo/Poster at <a href="http://www.thei3p.org/events/insider_workshop08.html">I3P Insider Threat Workshop 2008</a>.</li>
					</ul>
					<h5>Workshop Papers</h5>
					<ul>
						<li><B>Schall-Zimmerman, Z.</B>, & Camp, L. J. (2010). <i>Elder-friendly Design's Effects on Acceptance of Novel Technologies.</i> <a href="http://www.ece.nus.edu.sg/stfpage/eledbl/chi2010/">CHI 2010 Workshop on Senior-Friendly Technologies: Interaction Design for the Elderly.</a> April, 2010. <a href="http://zachzimm.com/research/Elder-friendly Design's Effects on Acceptance of Novel Technologies.pdf">View Draft</a></li>
					</ul>
					<br/><br/>
                </div>
             </div>
        </div>
        <div class="rightShadow">
        	<!-- Empty DIV for right drop shadow -->
        </div>
        <div id="footer">
        	<div class="bottomShadow">
            	<!-- Empty DIV for bottom drop shadow -->
               	<span>&copy; Copyright 2011 Zachary Zimmerman. All rights reserved. Site design by Zach and Celine Zimmerman</span>
            </div>
            <div id="footerContent">
            </div>
        </div>
    </div>

</body>
</html>
